using API.Infrastructure.Extensions;
using API.Models.Response;
using API.Swagger.Examples.Author;
using Application.DTOs.Author;
using Application.Interfaces;
using Application.Models;
using Asp.Versioning;
using Domain.Constants;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Filters;

namespace API.Controllers
{
    /// <summary>
    /// Manages operations for Authors in the library system.
    /// </summary>
    [ApiController]
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [Produces("application/json")]
    [Consumes("application/json")]
    public class AuthorController(
        IAuthorService authorService,
        IHashIdService hashIdService
        ) : ControllerBase
    {
        /// <summary>
        /// Retrieves a paginated list of authors.
        /// </summary>
        /// <param name="searchParams">Pagination and search filters.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A paged list of authors with HATEOAS links.</returns>
        [HttpGet]
        [AllowAnonymous]
        [ProducesResponseType(typeof(PagedResult<AuthorResponse>), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<PagedResult<AuthorResponse>>> GetAll(
            [FromQuery] AuthorSearchParameters searchParams,
            CancellationToken ct)
        {
            var dtos = await authorService.GetPagedAuthorsAsync(searchParams, ct);
            var response = dtos.Adapt<PagedResult<AuthorResponse>>();

            foreach (var author in response.Items)
            {
                author.AddStandardLinks(HttpContext, Url, author.AuthorId,
                    getRouteName: nameof(GetAuthorById),
                    deleteRouteName: nameof(DeleteAuthor),
                    updateRouteName: nameof(UpdateAuthor));
            }

            return Ok(response);
        }

        /// <summary>
        /// Retrieves a single author by their unique ID.
        /// </summary>
        /// <param name="id">The unique identifier of the author.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>The requested author details.</returns>
        [HttpGet("{id}", Name = nameof(GetAuthorById))]
        [AllowAnonymous]
        [ProducesResponseType(typeof(AuthorResponse), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [SwaggerResponseExample(StatusCodes.Status200OK, typeof(AuthorResponseExample))]
        public async Task<ActionResult<AuthorResponse>> GetAuthorById(string id, CancellationToken ct)
        {
            var internalId = hashIdService.Decode(id);

            var dto = await authorService.GetByIdAsync(internalId, ct);
            var response = dto.Adapt<AuthorResponse>();

            response.AddStandardLinks(HttpContext, Url, response.AuthorId,
                getRouteName: nameof(GetAuthorById),
                deleteRouteName: nameof(DeleteAuthor),
                updateRouteName: nameof(UpdateAuthor));

            return Ok(response);
        }

        /// <summary>
        /// Retrieves all books written by a specific author.
        /// </summary>
        /// <param name="id">The author's ID.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>A list of books.</returns>
        [HttpGet("{id}/books")]
        [AllowAnonymous]
        [ProducesResponseType(typeof(IEnumerable<BookResponse>), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<IEnumerable<BookResponse>>> GetBooksByAuthor(string id, CancellationToken ct)
        {
            var internalId = hashIdService.Decode(id);

            var bookDtos = await authorService.GetBooksByAuthorAsync(internalId, ct);
            var response = bookDtos.Adapt<IEnumerable<BookResponse>>();

            foreach (var book in response)
            {
                book.AddStandardLinks(HttpContext, Url, book.BookId,
                    getRouteName: "GetBookById",
                    deleteRouteName: "DeleteBook",
                    updateRouteName: "UpdateBook");
            }

            return Ok(response);
        }

        /// <summary>
        /// Creates a new author.
        /// </summary>
        /// <remarks>
        /// Don't include the ID in the request body; it is generated by the server.
        /// </remarks>
        /// <param name="createDto">The author creation payload.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>The newly created author.</returns>
        [HttpPost]
        [Authorize(Roles = Roles.Admin + "," + Roles.Librarian)]
        [ProducesResponseType(typeof(AuthorResponse), StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [SwaggerRequestExample(typeof(AuthorCreateDto), typeof(AuthorCreateExample))]
        [SwaggerResponseExample(StatusCodes.Status201Created, typeof(AuthorResponseExample))]
        public async Task<ActionResult<AuthorResponse>> CreateAuthor(
            [FromBody] AuthorCreateDto createDto,
            CancellationToken ct)
        {
            var createdDto = await authorService.CreateAuthorAsync(createDto, ct);
            var response = createdDto.Adapt<AuthorResponse>();

            response.AddStandardLinks(HttpContext, Url, response.AuthorId,
                getRouteName: nameof(GetAuthorById),
                deleteRouteName: nameof(DeleteAuthor),
                updateRouteName: nameof(UpdateAuthor));

            var version = HttpContext.GetRequestedApiVersion()?.ToString() ?? "1.0";

            return CreatedAtRoute(
                routeName: nameof(GetAuthorById),
                routeValues: new { id = response.AuthorId, version = version },
                value: response);
        }

        /// <summary>
        /// Updates an existing author.
        /// </summary>
        /// <param name="id">The ID of the author to update.</param>
        /// <param name="updateDto">The updated values.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>No content.</returns>
        [HttpPut("{id}", Name = nameof(UpdateAuthor))]
        [Authorize(Roles = Roles.Admin + "," + Roles.Librarian)]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [SwaggerRequestExample(typeof(AuthorUpdateDto), typeof(AuthorUpdateExample))]
        public async Task<IActionResult> UpdateAuthor(
            string id,
            [FromBody] AuthorUpdateDto updateDto,
            CancellationToken ct)
        {
            if (id != updateDto.AuthorId) return BadRequest("ID mismatch");

            await authorService.UpdateAuthorAsync(updateDto, ct);

            return NoContent();
        }

        /// <summary>
        /// Deletes an author.
        /// </summary>
        /// <remarks>
        /// This action cannot be undone. Any books associated with this author might restrict deletion.
        /// </remarks>
        /// <param name="id">The ID of the author to delete.</param>
        /// <param name="ct">Cancellation token.</param>
        /// <returns>No content.</returns>
        [HttpDelete("{id}", Name = nameof(DeleteAuthor))]
        [Authorize(Roles = Roles.Admin)]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> DeleteAuthor(string id, CancellationToken ct)
        {
            var internalId = hashIdService.Decode(id);

            await authorService.DeleteAuthorAsync(internalId, ct);
            return NoContent();
        }
    }
}